version: "3.7"
    
services:
  mongo:
    image: mongo:5
    volumes:
      - db_data:/data/db
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: foo
      MONGO_INIT_DB_ROOT_PASSWORD: bar
    
  app:
    build:
      context: ./app
      dockerfile: dockerfiles/pureNode.development
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      ENVIRONMENT: local
      DB_USER: foo
      DB_PASS: bar
      DB_HOST: mongo
    volumes:
      - "./app/src:/srv/src"
      - "./app/bin:/srv/bin"
    # depends_on:
    #   - mongo
    #   - redis

    redis:
      from: redis

  devops:
    build:
      context: ./devops
    volumes:
      # Store the history
      - devops_history:/root/bash_history
      # Volume in the repo rather than copying it
      - ./:/root/repo
      # Just in case we have any ssh to deal with
      - $HOME/.ssh:/root/.ssh
      # enable aws access
      - ~/.aws:/root/.aws

  nginx:
    build:
      context: ./app
      dockerfile: dockerfiles/nginx
    ports:
      - 8080:80

volumes:
  db_data:
  devops_history: