version: "3.8"
    
services:
  mongo:
    image: mongo:5
    volumes:
      - db_data:/data/db
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INIT_DB_ROOT_USERNAME: foo
      MONGO_INIT_DB_ROOT_PASSWORD: bar
    
  backend:
    build:
      context: ./app
      dockerfile: dockerfiles/pureNode.development
    command: npm run dev
    environment:
      ENVIRONMENT: local
      DB_USER: foo
      DB_PASS: bar
      DB_HOST: mongo
      BUILD_UI: false
    logging:
      driver: json-file
    ports:
      - "3001:3000"
    volumes:
      - "./app/src:/srv/src"
      - "./app/bin:/srv/bin"
  
  httpd:
    build:
      context: ./app
      dockerfile: dockerfiles/httpd
    ports:
      - "3000:80"
    environment:
      APP_BACKEND: backend
    logging:
      driver: none
    depends_on:
      - backend

  devops:
    build:
      context: ./devops
    volumes:
      # Store the history
      - devops_history:/root/bash_history
      # Volume in the repo rather than copying it
      - ./:/root/repo
      # Just in case we have any ssh to deal with
      - $HOME/.ssh:/root/.ssh
      # enable aws access
      - ~/.aws:/root/.aws

volumes:
  db_data:
  devops_history: